version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Building lms admin service...
      - cd java-api/LMSHAdmin
      - mvn install
      - cd ../..
artifacts:
  files:
    - java-api/LMSHAdmin/target/*.jar
    - java-api/LMSHAdmin/aws/*.sh
    - java-api/LMSHAdmin/appspec.yml
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'