/* CREATE */
const ADD_GENRE_STARTED = 'ADD_GENRE_STARTED';
const ADD_GENRE_SUCCESS = 'ADD_GENRE_SUCCESS';
const ADD_GENRE_FAILURE = 'ADD_GENRE_FAILURE';
/* UPDATE */
const UPDATE_GENRE_STARTED = 'UPDATE_GENRE_STARTED';
const UPDATE_GENRE_SUCCESS = 'UPDATE_GENRE_SUCCESS';
const UPDATE_GENRE_FAILURE = 'UPDATE_GENRE_FAILURE';
/* READ */
const GET_GENRES_STARTED = 'GET_GENRES_STARTED';
const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';

export {
  ADD_GENRE_STARTED,
  ADD_GENRE_SUCCESS,
  ADD_GENRE_FAILURE,
  GET_GENRES_STARTED,
  GET_GENRES_SUCCESS,
  GET_GENRES_FAILURE,
  UPDATE_GENRE_STARTED,
  UPDATE_GENRE_SUCCESS,
  UPDATE_GENRE_FAILURE,
};
