const GET_GENRES_STARTED = 'GET_GENRES_STARTED';
const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';

export {
  GET_GENRES_STARTED,
  GET_GENRES_SUCCESS,
  GET_GENRES_FAILURE,
};
