// Reading
const GET_PUBLISHERS_STARTED = 'GET_PUBLISHERS_STARTED';
const GET_PUBLISHERS_SUCCESS = 'GET_PUBLISHERS_SUCCESS';
const GET_PUBLISHERS_FAILURE = 'GET_PUBLISHERS_FAILURE';

// Adding
const ADD_PUBLISHER_STARTED = 'ADD_PUBLISHER_STARTED';
const ADD_PUBLISHER_SUCCESS = 'ADD_PUBLISHER_SUCCESS';
const ADD_PUBLISHER_FAILURE = 'ADD_PUBLISHER_FAILURE';

//Updating
const UPDATE_PUBLISHER_STARTED = 'UPDATE_PUBLISHER_STARTED';
const UPDATE_PUBLISHER_SUCCESS = 'UPDATE_PUBLISHER_SUCCESS';
const UPDATE_PUBLISHER_FAILURE = 'UPDATE_PUBLISHER_FAILURE';

// Deleting
const DELETE_PUBLISHER_STARTED = 'DELETE_PUBLISHER_STARTED';
const DELETE_PUBLISHER_SUCCESS = 'DELETE_PUBLISHER_SUCCESS';
const DELETE_PUBLISHER_FAILURE = 'DELETE_PUBLISHER_FAILURE';

export {
    GET_PUBLISHERS_STARTED,
    GET_PUBLISHERS_SUCCESS,
    GET_PUBLISHERS_FAILURE,
    ADD_PUBLISHER_STARTED,
    ADD_PUBLISHER_SUCCESS,
    ADD_PUBLISHER_FAILURE,
    UPDATE_PUBLISHER_STARTED,
    UPDATE_PUBLISHER_SUCCESS,
    UPDATE_PUBLISHER_FAILURE,
    DELETE_PUBLISHER_STARTED,
    DELETE_PUBLISHER_SUCCESS,
    DELETE_PUBLISHER_FAILURE
}
