// Reading
const GET_PUBLISHERS_STARTED = 'GET_PUBLISHERS_STARTED';
const GET_PUBLISHERS_SUCCESS = 'GET_PUBLISHERS_SUCCESS';
const GET_PUBLISHERS_FAILURE = 'GET_PUBLISHERS_FAILURE';

// Adding

//Updating

export {
    GET_PUBLISHERS_STARTED,
    GET_PUBLISHERS_SUCCESS,
    GET_PUBLISHERS_FAILURE
}
