const GET_BRANCHES_STARTED = 'GET_BRANCHES_STARTED';
const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
const GET_BRANCHES_FAILURE = 'GET_BRANCHES_FAILURE';

export {
  GET_BRANCHES_STARTED,
  GET_BRANCHES_SUCCESS,
  GET_BRANCHES_FAILURE,
};
