/* CREATE */
const ADD_BRANCH_STARTED = 'ADD_BRANCH_STARTED';
const ADD_BRANCH_SUCCESS = 'ADD_BRANCH_SUCCESS';
const ADD_BRANCH_FAILURE = 'ADD_BRANCH_FAILURE';
/* UPDATE */
const UPDATE_BRANCH_STARTED = 'UPDATE_BRANCH_STARTED';
const UPDATE_BRANCH_SUCCESS = 'UPDATE_BRANCH_SUCCESS';
const UPDATE_BRANCH_FAILURE = 'UPDATE_BRANCH_FAILURE';
/* READ */
const GET_BRANCHES_STARTED = 'GET_BRANCHES_STARTED';
const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
const GET_BRANCHES_FAILURE = 'GET_BRANCHES_FAILURE';

export {
  ADD_BRANCH_STARTED,
  ADD_BRANCH_SUCCESS,
  ADD_BRANCH_FAILURE,
  GET_BRANCHES_STARTED,
  GET_BRANCHES_SUCCESS,
  GET_BRANCHES_FAILURE,
  UPDATE_BRANCH_STARTED,
  UPDATE_BRANCH_SUCCESS,
  UPDATE_BRANCH_FAILURE,
};
