/* CREATE */
// const ADD_AUTHOR_STARTED = 'ADD_AUTHOR_STARTED';
// const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS';
// const ADD_AUTHOR_FAILURE = 'ADD_AUTHOR_FAILURE';
/* UPDATE */
// const UPDATE_AUTHOR_STARTED = 'UPDATE_AUTHOR_STARTED';
// const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
// const UPDATE_AUTHOR_FAILURE = 'UPDATE_AUTHOR_FAILURE';
/* DELETE */
// const DELETE_AUTHOR_STARTED = 'DELETE_AUTHOR_STARTED';
// const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';
// const DELETE_AUTHOR_FAILURE = 'DELETE_AUTHOR_FAILURE';
/* READ */
const GET_AUTHORS_STARTED = 'GET_AUTHORS_STARTED';
const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
const GET_AUTHORS_FAILURE = 'GET_AUTHORS_FAILURE';

export {
  // ADD_AUTHOR_STARTED,
  // ADD_AUTHOR_SUCCESS,
  // ADD_AUTHOR_FAILURE,
  // DELETE_AUTHOR_STARTED,
  // DELETE_AUTHOR_SUCCESS,
  // DELETE_AUTHOR_FAILURE,
  GET_AUTHORS_STARTED,
  GET_AUTHORS_SUCCESS,
  GET_AUTHORS_FAILURE,
  // UPDATE_AUTHOR_STARTED,
  // UPDATE_AUTHOR_SUCCESS,
  // UPDATE_AUTHOR_FAILURE,
};
