// Reading
const GET_BORROWERS_STARTED = 'GET_BORROWERS_STARTED';
const GET_BORROWERS_SUCCESS = 'GET_BORROWERS_SUCCESS';
const GET_BORROWERS_FAILURE = 'GET_BORROWERS_FAILURE';

//Adding
const ADD_BORROWER_STARTED = 'ADD_BORROWER_STARTED';
const ADD_BORROWER_SUCCESS = 'ADD_BORROWER_SUCCESS';
const ADD_BORROWER_FAILURE = 'ADD_BORROWER_FAILURE';

//Updating
const UPDATE_BORROWER_STARTED = 'UPDATE_BORROWER_STARTED';
const UPDATE_BORROWER_SUCCESS = 'UPDATE_BORROWER_SUCCESS';
const UPDATE_BORROWER_FAILURE = 'UPDATE_BORROWER_FAILURE';

//Deleting
const DELETE_BORROWER_STARTED = 'DELETE_BORROWER_STARTED';
const DELETE_BORROWER_SUCCESS = 'DELETE_BORROWER_SUCCESS';
const DELETE_BORROWER_FAILURE = 'DELETE_BORROWER_FAILURE';

export {
    GET_BORROWERS_STARTED,
    GET_BORROWERS_SUCCESS,
    GET_BORROWERS_FAILURE,
    ADD_BORROWER_STARTED,
    ADD_BORROWER_SUCCESS,
    ADD_BORROWER_FAILURE,
    UPDATE_BORROWER_STARTED,
    UPDATE_BORROWER_SUCCESS,
    UPDATE_BORROWER_FAILURE,
    DELETE_BORROWER_STARTED,
    DELETE_BORROWER_SUCCESS,
    DELETE_BORROWER_FAILURE
}
