// reading all loans

const GET_LOANS_STARTED = 'GET_LOANS_STARTED';
const GET_LOANS_SUCCESS = 'GET_LOANS_SUCCESS';
const GET_LOANS_FAILURE = 'GET_LOANS_FAILURE';

export {
  GET_LOANS_STARTED,
  GET_LOANS_SUCCESS,
  GET_LOANS_FAILURE,
};
