// reading all loans

const GET_LOANS_STARTED = 'GET_LOANS_STARTED';
const GET_LOANS_SUCCESS = 'GET_LOANS_SUCCESS';
const GET_LOANS_FAILURE = 'GET_LOANS_FAILURE';

const OVERRIDE_STARTED = 'OVERRIDE_STARTED';
const OVERRIDE_SUCCESS = 'OVERRIDE_SUCCESS';
const OVERRIDE_FAILURE = 'OVERRIDE_FAILURE';

export {
    GET_LOANS_STARTED,
    GET_LOANS_SUCCESS,
    GET_LOANS_FAILURE,
    OVERRIDE_STARTED,
    OVERRIDE_SUCCESS,
    OVERRIDE_FAILURE
}
