
/* READ */
const GET_BOOKS_STARTED = 'GET_BOOKS_STARTED';
const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';
/* READ Copies */
const GET_BOOKCOPIES_STARTED = 'GET_BOOKCOPIES_STARTED';
const GET_BOOKCOPIES_SUCCESS = 'GET_BOOKCOPIES_SUCCESS';
const GET_BOOKCOPIES_FAILURE = 'GET_BOOKCOPIES_FAILURE';

export {
  GET_BOOKS_STARTED,
  GET_BOOKS_SUCCESS,
  GET_BOOKS_FAILURE,
  GET_BOOKCOPIES_STARTED,
  GET_BOOKCOPIES_SUCCESS,
  GET_BOOKCOPIES_FAILURE,
};
