
/* READ */
const GET_BBOOKS_STARTED = 'GET_BBOOKS_STARTED';
const GET_BBOOKS_SUCCESS = 'GET_BBOOKS_SUCCESS';
const GET_BBOOKS_FAILURE = 'GET_BBOOKS_FAILURE';
/* READ Copies */
const GET_BOOKCOPIES_STARTED = 'GET_BOOKCOPIES_STARTED';
const GET_BOOKCOPIES_SUCCESS = 'GET_BOOKCOPIES_SUCCESS';
const GET_BOOKCOPIES_FAILURE = 'GET_BOOKCOPIES_FAILURE';

export {
  GET_BBOOKS_STARTED,
  GET_BBOOKS_SUCCESS,
  GET_BBOOKS_FAILURE,
  GET_BOOKCOPIES_STARTED,
  GET_BOOKCOPIES_SUCCESS,
  GET_BOOKCOPIES_FAILURE,
};
