version: "3"

services: 
  lms-admin-service-db:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=library
    ports:
      - 0.0.0.0:7201:3306
  lms-admin-service:
    build: 
      context: ./LMSHAdmin/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-boot-mysql-network
    depends_on: 
      - lms-admin-service-db
  lms-borrower-service:
    build: 
      context: ./LMSHBorrower/
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - spring-boot-mysql-network
    depends_on: 
      - lms-admin-service-db

networks:
  spring-boot-mysql-network:
    driver: bridge