/* CREATE */
const ADD_BOOK_STARTED = 'ADD_BOOK_STARTED';
const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
/* UPDATE */
const UPDATE_BOOK_STARTED = 'UPDATE_BOOK_STARTED';
const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
/* DELETE */
const DELETE_BOOK_STARTED = 'DELETE_BOOK_STARTED';
const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
/* READ */
const GET_BOOKS_STARTED = 'GET_BOOKS_STARTED';
const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';

export {
  ADD_BOOK_STARTED,
  ADD_BOOK_SUCCESS,
  ADD_BOOK_FAILURE,
  DELETE_BOOK_STARTED,
  DELETE_BOOK_SUCCESS,
  DELETE_BOOK_FAILURE,
  GET_BOOKS_STARTED,
  GET_BOOKS_SUCCESS,
  GET_BOOKS_FAILURE,
  UPDATE_BOOK_STARTED,
  UPDATE_BOOK_SUCCESS,
  UPDATE_BOOK_FAILURE,
};
