const GET_COPIES_STARTED = 'GET_COPIES_STARTED';
const GET_COPIES_SUCCESS = 'GET_COPIES_SUCCESS';
const GET_COPIES_FAILURE = 'GET_COPIES_FAILURE';

const GET_BRANCH_BOOKS_STARTED = 'GET_BRANCH_BOOKS_STARTED';
const GET_BRANCH_BOOKS_SUCCESS = 'GET_BRANCH_BOOKS_SUCCESS';
const GET_BRANCH_BOOKS_FAILURE = 'GET_BRANCH_BOOKS_FAILURE';

const EDIT_BOOK_COPIES_STARTED = 'EDIT_BOOK_COPIES_STARTED';
const EDIT_BOOK_COPIES_SUCCESS = 'EDIT_BOOK_COPIES_SUCCESS';
const EDIT_BOOK_COPIES_FAILURE = 'EDIT_BOOK_COPIES_FAILURE';

export {
    GET_COPIES_STARTED,
    GET_COPIES_SUCCESS,
    GET_COPIES_FAILURE,
    GET_BRANCH_BOOKS_STARTED,
    GET_BRANCH_BOOKS_SUCCESS,
    GET_BRANCH_BOOKS_FAILURE,
    EDIT_BOOK_COPIES_STARTED,
    EDIT_BOOK_COPIES_SUCCESS,
    EDIT_BOOK_COPIES_FAILURE
}
